# Generated by Django 3.0.6 on 2020-06-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200612_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='archived',
            new_name='arquivado',
        ),
    ]
