# Generated by Django 2.2.13 on 2020-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('critical', 'critical'), ('debug', 'debug'), ('error', 'error'), ('warning', 'warning'), ('information', 'info')], max_length=20),
        ),
    ]
